apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackjack
  template:
    metadata:
      labels:
        app: blackjack
    spec:
      containers:
      - name: blackjack
        image: flaviab447/blackjack-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blackjack-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: blackjack
